namespace CoachBoard.Application.DTOs;

public record ExerciseCreateDto(
    string Name,
    string Category,
    int? DefaultSets,
    int? DefaultReps,
    int? CoachId = null,
    bool IsGlobal = false,
    string? Description = null,
    string? Instructions = null,
    string? ImageUrl = null,
    string? VideoUrl = null,
    string? ReferenceUrl = null,
    string? DifficultyLevel = null,
    string? MovementPattern = null,
    string? Equipment = null,
    string? TargetMuscleGroup = null,
    string? SecondaryMuscleGroups = null,
    string? ExerciseType = null,
    string? Environment = null,
    string? Tags = null,
    bool IsActive = true);

public record ExerciseUpdateDto(
    string Name,
    string Category,
    int? DefaultSets,
    int? DefaultReps,
    int? CoachId = null,
    bool IsGlobal = false,
    string? Description = null,
    string? Instructions = null,
    string? ImageUrl = null,
    string? VideoUrl = null,
    string? ReferenceUrl = null,
    string? DifficultyLevel = null,
    string? MovementPattern = null,
    string? Equipment = null,
    string? TargetMuscleGroup = null,
    string? SecondaryMuscleGroups = null,
    string? ExerciseType = null,
    string? Environment = null,
    string? Tags = null,
    bool IsActive = true);

public record ExerciseReadDto(
    int Id,
    int? CoachId,
    bool IsGlobal,
    string Name,
    string Category,
    int? DefaultSets,
    int? DefaultReps,
    string? Description,
    string? Instructions,
    string? ImageUrl,
    string? VideoUrl,
    string? ReferenceUrl,
    string? DifficultyLevel,
    string? MovementPattern,
    string? Equipment,
    string? TargetMuscleGroup,
    string? SecondaryMuscleGroups,
    string? ExerciseType,
    string? Environment,
    string? Tags,
    bool IsActive,
    DateTime CreatedAt);
