name: Deploy CoachBoard API to Azure Web App

on:
  push:
    branches:
      - main  # o la rama que uses
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: coachboard-api-g4d2a7bpf5age4b0 # <-- nombre exacto de tu Web App en Azure
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        working-directory: ./src/CoachBoard.Api
        run: dotnet restore

      - name: Build
        working-directory: ./src/CoachBoard.Api
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        working-directory: ./src/CoachBoard.Api
        run: dotnet publish --configuration Release --no-build --output ../../publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
